### ISSUE TITLE
PSF.fits files

### ISSUE THREAD

**Issue by parlange** [kuanweih/strong_lensing_vit_resnet#22]
Hi @kuanweih 

Thank you for sharing your ViT implementation.

I am trying to generate a dataset using **Lenstronomy_simulation_dev.ipynb**

Are these PSF fits files publicly available?

``````
    if i < mark:
      Real_PSF=fits.getdata('/content/drive/MyDrive/PSF/J0924_AO_PSF_20mas.fits')
    elif i >= mark and i < 2*mark:
      Real_PSF=fits.getdata('/content/drive/MyDrive/PSF/HE0435_AO_PSF_20mas.fits')
    elif i >= 2*mark and i < 3*mark:
      Real_PSF=fits.getdata('/content/drive/MyDrive/PSF/PG1115_AO_PSF_20mas.fits')
    elif i >= 3*mark and i < 4*mark:
      Real_PSF=fits.getdata('/content/drive/MyDrive/PSF/PSF_-2_6.fitsnew.fits')
    elif i >= 4*mark and i < 5*mark:
      Real_PSF=fits.getdata('/content/drive/MyDrive/PSF/PSF_-1_4.fitsnew.fits')
    elif i >= 5*mark and i < 6*mark:
      Real_PSF=fits.getdata('/content/drive/MyDrive/PSF/PSF_-0.5_0.fitsnew.fits')
``````

**Comment by kuanweih** [comment]
@geoffcfchen @joshualin24 Do you have those files?

**Comment by geoffcfchen** [comment]
Hi @kuanweih and @parlange 

You can get the files from here
https://drive.google.com/drive/folders/1v5UJxSiahPm11UGBFYjQtkCQ4fAs8voX?usp=sharing

If you use these files to publish papers, please cite 
https://academic.oup.com/mnras/article/513/2/2349/6575038?login=false
https://academic.oup.com/mnras/article/490/2/1743/5568378?login=false
https://academic.oup.com/mnras/article/462/4/3457/2590006

**Comment by parlange** [comment]
Thank you very much @kuanweih @geoffcfchen 

I've been working on detection and modelling of strong gravitational lenses with CNN and BNN.

I will cite your work with ViT and lenstronomy PSFs, and share it with my advisors, who do research with time delay for cosmology on LSST, DESC, SLSC.

**Comment by kuanweih** [comment]
@geoffcfchen: Thank you for providing the links! 
@parlange: Happy to help and all the best to your research projects! Will follow closely 😃
